"""Config file: here resides the bot token"""

TOKEN = "tokenplaceholder"
UPDATES_TIMEOUT = 50
MAX_REPLY_LENGTH = 150
ECELEBS = [
    {
        "url": "urlplaceholder",
        "regex": r"regexplaceholder",
        "prefix": "prefixplaceholder",
    },
]
FBI_WORDS = ["wordplaceholder"]
REVOLVER_CHAMBERS = 6
REVOLVER_BULLETS = 1
PASTAS = {"pastaname": "pasta text"}
CAPTCHA_BACKGROUND_COLOR = (0, 0, 0)
CAPTCHA_TEXT_COLOR = (255, 255, 255)
CAPTCHA_LINES_COLOR = (255, 255, 255)
CAPTCHA_DOTS_COLOR = (255, 255, 255)
CAPTCHA_CHARACTERS = "23456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ"
CAPTCHA_WIDTH = 720
CAPTCHA_HEIGHT = 180
CAPTCHA_FONT = "./FreeSans.ttf"
CAPTCHA_FONT_SIZE = 60
CAPTCHA_MAX_ROTATION_ANGLE = 45
CAPTCHA_LETTER_TOP_PADDING = 60
CAPTCHA_LETTER_LEFT_PADDING = 40
CAPTCHA_LINES_NUMBER = 50
CAPTCHA_DOTS_NUMBER = 1000
CAPTCHA_LENGTH = 5
CAPTCHA_EXPIRATION = 600
CAPTCHA_RANDOMIZE_TEXT_COLORS = False
CAPTCHA_RANDOMIZE_LINES_COLORS = False
CAPTCHA_RANDOMIZE_DOTS_COLORS = False
CAPTCHA_LINES_START_FROM_BORDER = True
CAPTCHA_USE_BORDER_LINEAR_RANDOMNESS = False
