"""Config file: here resides the bot token"""

TOKEN = "tokenplaceholder"
OWNER_ID = 1234567890
OFFLINE_ANTIFLOOD_TIMEOUT = 300
UPDATES_TIMEOUT = 50
UPDATE_PROCESSING_MAX_TIMEOUT = 120
OUTGOING_REQUESTS_TIMEOUT = 3
MAX_REPLY_LENGTH = 500
ECELEBS = [
    {
        "url": "urlplaceholder",
        "regex": r"regexplaceholder",
        "prefix": "prefixplaceholder",
    },
]
FBI_WORDS = ["wordplaceholder"]
FBI_MOST_WANTED_NUMBER = 5
REVOLVER_CHAMBERS = 6
REVOLVER_BULLETS = 1
PASTAS = {"pastaname": "pasta text"}
CAPTCHA_BACKGROUND_COLOR = (0, 0, 0)
CAPTCHA_TEXT_COLOR = (255, 255, 255)
CAPTCHA_LINES_COLOR = (255, 255, 255)
CAPTCHA_DOTS_COLOR = (255, 255, 255)
CAPTCHA_CHARACTERS = "23456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ"
CAPTCHA_WIDTH = 720
CAPTCHA_HEIGHT = 360
CAPTCHA_FONT = "./FreeSans.ttf"
CAPTCHA_FONT_SIZE = 90
CAPTCHA_MAX_ROTATION_ANGLE = 45
CAPTCHA_LETTER_TOP_PADDING = 160
CAPTCHA_LETTER_LEFT_PADDING = 40
CAPTCHA_LINES_NUMBER = 200
CAPTCHA_DOTS_NUMBER = 1000
CAPTCHA_LENGTH = 5
CAPTCHA_RANDOMIZE_TEXT_COLORS = False
CAPTCHA_RANDOMIZE_LINES_COLORS = False
CAPTCHA_RANDOMIZE_DOTS_COLORS = False
CAPTCHA_LINES_START_FROM_BORDER = True
CAPTCHA_USE_BORDER_LINEAR_RANDOMNESS = False
CAPTCHA_KEYBOARD_BUTTONS_PER_LINE = 3
CAPTCHA_LINE_WIDTH = 1
CAPTCHA_EXTRA_TEXTS_NUMBER = 7
CAPTCHA_EXPIRATION = 300
ALLOW_PRIVATE_MESSAGES = False
MESSAGES_CHAT_RATE_NUMBER = 18
MESSAGES_CHAT_RATE_PERIOD = 60
MESSAGES_USER_RATE_NUMBER = 50
MESSAGES_USER_RATE_PERIOD = 60
